export const TODOS = {
    FETCH: 'FETCH_TODOS',
    FETCH_FAIL: 'FETCH_TODOS_FAIL',
    LOADING: 'TODOS_LOADING',
    ADD: 'ADD_TODO',
    ADD_FAIL: 'ADD_TODO_FAIL',
    REMOVE: 'REMOVE_TODO',
    REMOVE_FAIL: 'REMOVE_TODO_FAIL',
    TOGGLE: 'TOGGLE_TODO',
    TOGGLE_FAIL: 'TOGGLE_TODO_FAIL',
    ERASE: 'ERASE_TODOS'
};

export const ERROR = {
    GET: 'GET_ERROR',
    CLEAR: 'CLEAR_ERROR'
};

export const AUTH = {
    REGISTER: 'REGISTER',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN: 'LOGIN',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',
    LOAD_USER: 'LOAD_USER',
    LOAD_USER_FAIL: 'LOAD_USER_FAIL',
    USER_LOADING: 'USER_LOADING',
    DELETE_USER: 'DELETE_USER',
    DELETE_USER_FAIL: 'DELETE_USER_FAIL',
    REFRESH: 'REFRESH',
    REFRESH_FAIL: 'REFRESH_FAIL'
};